# Generated by Django 4.1 on 2026-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='ojt_training_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='ojt_training_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='ojt_training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='pra_training_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='pra_training_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='pra_training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='safety_training_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='safety_training_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='safety_training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='technical_training_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='technical_training_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='technical_training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='total_completion_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='total_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='training_need_to_completed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employees',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employees',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
